- name: Declare variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: Declare variable in another file
  hosts: all
  connection: local
  vars_file:
    - var.yml
  tasks:
    - name: Access a Variable
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: Declare variable at play level
  hosts: all
  connection: local
  tasks:
    - name: Access a variable
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: task.example.com